version: '2.0'
services:
  daemon:
    build: .
    container_name: cron
    volumes:
      - ./cron.hourly:/etc/cron.hourly
      - ./cron.daily:/etc/cron.daily
      - ./cron.weekly:/etc/cron.weekly
      - ./cron.monthly:/etc/cron.monthly
      - ./cron.reboot:/etc/cron.reboot
      - ./logs:/var/log/cron
    restart: always
