version: '3.5'

networks:
  cron:
    name: cron

services:
  cron:
    build: .
    container_name: cron
    networks:
      - cron
    env_file:
      - main.env
    volumes:
      - ./cron/hourly:/etc/cron.hourly
      - ./cron/daily:/etc/cron.daily
      - ./cron/weekly:/etc/cron.weekly
      - ./cron/monthly:/etc/cron.monthly
      - ./cron/reboot:/etc/cron.reboot
      - ./cron/start:/etc/cron.start
      - ./cron/logs:/var/log/cron
    restart: always
