version: '3.8'
services:
  cron:
    build: .
    container_name: cron
    volumes:
      - ./cron.hourly:/etc/cron.hourly
      - ./cron.daily:/etc/cron.daily
      - ./cron.weekly:/etc/cron.weekly
      - ./cron.monthly:/etc/cron.monthly
      - ./cron.logs:/var/log/cron
    restart: unless-stopped:0
